# Automatically created by: shub deploy

from setuptools import setup, find_packages

setup(
    name             = 'project',
    version          = '1.0',
    packages         = find_packages(),
    entry_points     = {'scrapy': ['settings = mfma.settings']},
    install_requires = [
        'attrs==16.3.0',
        'backports.ssl-match-hostname==3.5.0.1',
        'beautifulsoup4==4.4.1',
        'boto==2.45.0',
        'cffi==1.9.1',
        'click==6.7',
        'constantly==15.1.0',
        'cryptography==1.7.1',
        'cssselect==1.0.1',
        'docker-py==1.10.6',
        'docker-pycreds==0.2.1',
        'enum34==1.1.6',
        'idna==2.2',
        'incremental==16.10.1',
        'ipaddress==1.0.18',
        'lxml==3.7.2',
        'parsel==1.1.0',
        'pyasn1==0.1.9',
        'pyasn1-modules==0.0.8',
        'pycparser==2.17',
        'PyDispatcher==2.0.5',
        'pyOpenSSL==16.2.0',
        'PyYAML==3.12',
        'queuelib==1.4.2',
        'requests==2.12.4',
        'retrying==1.3.3',
        'scrapinghub==1.9.0',
        'Scrapy==1.3.0',
        'service-identity==16.0.0',
        'shub==2.5.0',
        'six==1.10.0',
        'Twisted==16.6.0',
        'w3lib==1.16.0',
        'websocket-client==0.40.0',
        'zope.interface==4.3.3',
    ],
)
